### -----------------ADMIN-------------------

### Register Admin
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "name": "Manpreet",
  "email": "admin@gmail.com",
  "password": "1234",
  "role": "ROLE_ADMIN"
}


### ADMIN TOKEN
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "1234"
}

### ---------------------------USER-------------------
### REGISTER USER
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "name": "Manpreet",
  "email": "user@gmail.com",
  "password": "1234",
  "role": "ROLE_USER"
}

### Login (user TOKEN)
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "1234"
}

### ---------------------------------------------QUESTIONS-----------------------------------------


### QUESTIONS

### Add Question (Protected)
POST http://localhost:8080/questions
Content-Type: application/json
Authorization: Bearer YOUR  TOKEN HERE

{
  "title": "Test",
  "description": "Test",
  "topic": "Java",
  "difficulty": "Easy",
  "correctAnswer": "Test"
}

### Get All Questions (Protected)
GET http://localhost:8080/questions
Authorization: Bearer TOKEN 


### Submit Attempt (Protected)
POST http://localhost:8080/attempts
Content-Type: application/json
Authorization: Bearer TOKEN

{
  "userId": 1,
  "questionId": 1,
  "userAnswer": "Java is an object-oriented programming language"
}


### PROFILE

### Get Logged-in User (Protected)
GET http://localhost:8080/users/profile
Authorization: Bearer TOKEN

#### AI GENERATED QUESTIONS
POST http://localhost:8080/ai/generate
Content-Type: application/json

{
  "skills": "Java, Spring Boot",
  "projects": "AI Interview Platform",
  "experience": "Internship",
  "technologies": "React, MySQL"
}






##### live testing link: https://backend-quiz-app.onrender.com

### REGISTER ADMIN
POST https://interview-backend-3n8v.onrender.com/users/register
Content-Type: application/json

{
  "name": "Manpreet",
  "email": "admin@gmail.com",
  "password": "admin123",
  "role": "ROLE_ADMIN"
}
 

 ### ADMIN TOKEN

POST https://interview-backend-3n8v.onrender.com/users/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin123"
}



### REGISTER USER
POST https://interview-backend-3n8v.onrender.com/users/register
Content-Type: application/json

{
  "name": "Manpreet",
  "email": "manpreet@gmail.com",
  "password": "1234",
  "role": "ROLE_USER"
}

### Login (user TOKEN)
POST https://interview-backend-3n8v.onrender.com/users/login
Content-Type: application/json

{
  "email": "manpreet@gmail.com",
  "password": "1234"
}

### GET QUESTIONS
GET https://interview-backend-3n8v.onrender.com/questions
Authorization: Bearer YOUR  TOKEN HERE

### Add Question (Protected)
POST https://interview-backend-3n8v.onrender.com/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc3NzU0NTYxMSwiZXhwIjoxNzc3NTQ5MjExfQ.5FC2Z_gMI0lKffa18lVMJt9nRTqC9OPH8PEfMDXYUQ0 
Content-Type: application/json

{
  "title": "What is Java?",
  "description": "Explain OOP in Java"
}